version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - todo-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - todo-network
    depends_on:
      - backend

networks:
  todo-network:
    driver: bridge
